"""change shopping items table to todo items table

Revision ID: 1302584e8494
Revises: f53395e40357
Create Date: 2025-07-08 15:31:12.638269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1302584e8494'
down_revision: Union[str, None] = 'f53395e40357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('categories', sa.String(length=255), nullable=True),
    sa.Column('shops', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('todo_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_todo_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_todo_items_name'), ['name'], unique=False)

    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.drop_index('ix_shopping_items_id')
        batch_op.drop_index('ix_shopping_items_name')

    op.drop_table('shopping_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_closed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('categories', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('shops', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='shopping_items_pkey')
    )
    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.create_index('ix_shopping_items_name', ['name'], unique=False)
        batch_op.create_index('ix_shopping_items_id', ['id'], unique=False)

    with op.batch_alter_table('todo_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todo_items_name'))
        batch_op.drop_index(batch_op.f('ix_todo_items_id'))

    op.drop_table('todo_items')
    # ### end Alembic commands ###
