"""create_access_and_refresh_token_tables

Revision ID: 3a778cea0867
Revises: 1a4a698287ce
Create Date: 2025-07-18 23:44:33.524039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a778cea0867'
down_revision: Union[str, None] = '1a4a698287ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_tokens',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('jti', sa.String(length=255), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('expires_at', sa.DateTime(), nullable=False),
                    sa.Column('is_revoked', sa.Boolean(), nullable=False),
                    sa.Column('last_used_at', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('access_tokens', schema=None) as batch_op:
        batch_op.create_index('idx_access_tokens_jti_revoked', [
                              'jti', 'is_revoked'], unique=False)
        batch_op.create_index('idx_access_tokens_user_expires', [
                              'user_id', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_tokens_expires_at'), [
                              'expires_at'], unique=False)
        batch_op.create_index(batch_op.f(
            'ix_access_tokens_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_access_tokens_user_id'), [
                              'user_id'], unique=False)

    op.create_table('refresh_tokens',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('jti', sa.String(length=255), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('expires_at', sa.DateTime(), nullable=False),
                    sa.Column('is_revoked', sa.Boolean(), nullable=False),
                    sa.Column('last_used_at', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index('idx_refresh_tokens_jti_revoked', [
                              'jti', 'is_revoked'], unique=False)
        batch_op.create_index('idx_refresh_tokens_user_expires', [
                              'user_id', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_expires_at'), [
                              'expires_at'], unique=False)
        batch_op.create_index(batch_op.f(
            'ix_refresh_tokens_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), [
                              'user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_jti'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_expires_at'))
        batch_op.drop_index('idx_refresh_tokens_user_expires')
        batch_op.drop_index('idx_refresh_tokens_jti_revoked')

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('access_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_access_tokens_jti'))
        batch_op.drop_index(batch_op.f('ix_access_tokens_expires_at'))
        batch_op.drop_index('idx_access_tokens_user_expires')
        batch_op.drop_index('idx_access_tokens_jti_revoked')

    op.drop_table('access_tokens')
    # ### end Alembic commands ###
