"""Add items to TodoProject table and set project_id to NULL if project gets removed

Revision ID: e5be391de3fe
Revises: f7106ccf1432
Create Date: 2025-07-09 14:56:12.510162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5be391de3fe'
down_revision: Union[str, None] = 'f7106ccf1432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_items', schema=None) as batch_op:
        batch_op.drop_constraint('todo_items_project_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'todo_projects', ['project_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('todo_items_project_id_fkey', 'todo_projects', ['project_id'], ['id'])

    # ### end Alembic commands ###
