"""create shopping items table

Revision ID: f53395e40357
Revises: a078aff9a677
Create Date: 2025-05-20 13:49:05.440453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f53395e40357'
down_revision: Union[str, None] = 'a078aff9a677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('categories', sa.String(length=255), nullable=True),
    sa.Column('shops', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopping_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shopping_items_name'), ['name'], unique=False)

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)

    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopping_items_name'))
        batch_op.drop_index(batch_op.f('ix_shopping_items_id'))

    op.drop_table('shopping_items')
    # ### end Alembic commands ###
