"""Replace category todo table with project table

Revision ID: f7106ccf1432
Revises: 1302584e8494
Create Date: 2025-07-08 16:35:15.398926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7106ccf1432'
down_revision: Union[str, None] = '1302584e8494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('todo_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_todo_projects_id'), ['id'], unique=False)

    with op.batch_alter_table('todo_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'todo_projects', ['project_id'], ['id'])
        batch_op.drop_column('categories')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('todo_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todo_projects_id'))

    op.drop_table('todo_projects')
    # ### end Alembic commands ###
