name: Test & Deploy to Raspberry Pi

on:
  push:
    branches: [master]

jobs:
  test:
    uses: ./.github/workflows/poetry-test.yml

  deploy:
    needs: test
    uses: ./.github/workflows/deploy-raspberry-pi.yml
