name: Test & Deploy to Raspberry Pi (Legacy)

on:
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deployment using legacy workflow'
        required: false
        default: false
        type: boolean

jobs:
  test:
    uses: ./.github/workflows/checks.yml

  deploy:
    needs: test
    uses: ./.github/workflows/deploy-to-production.yml
    secrets: inherit
